#!/bin/bash
BASE_DIR=`pwd`
INPUT_FILE=$BASE_DIR/data/wsj00.stagged.0.01.100
OUTPUT_FILE=$BASE_DIR/output/parser.beam.out
LOG_FILE=$BASE_DIR/output/parser.beam.log
WEIGHTS_FILE=$BASE_DIR/data/weights.beam

STDOUT_LOG=$BASE_DIR/output/parser.beam.more.log
FROM_SENT=1
TO_SENT=2000

PRINTER=grs

sh ./compile
java -classpath bin -Xms64g -Xmx64g ParserBeam $INPUT_FILE $OUTPUT_FILE $LOG_FILE $WEIGHTS_FILE $FROM_SENT $TO_SENT $PRINTER > $STDOUT_LOG

# experimental branch: ParserBeam, trove, koloboke
#java -classpath bin:lib/trove-3.0.3.jar:lib/koloboke-api-jdk6-7-0.6.6.jar:lib/koloboke-impl-jdk6-7-0.6.6.jar -Xms64g -Xmx64g -verbose:gc -Xloggc:output/parser.beam.gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps ParserBeam $INPUT_FILE $OUTPUT_FILE $LOG_FILE $WEIGHTS_FILE $FROM_SENT $TO_SENT > $STDOUT_LOG

# baseline branch: ParserBeam
#java -classpath bin -Xms64g -Xmx64g -verbose:gc -Xloggc:output/parser.beam.gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps ParserBeam $INPUT_FILE $OUTPUT_FILE $LOG_FILE $WEIGHTS_FILE > $STDOUT_LOG
